### ISSUE TITLE
Codebook

### ISSUE THREAD

**Issue by apoorvalal** [justinelliotmeyers/official_bihar_india_village_boundary_shapefile#1]
Hi Justin, 
Thanks for collecting all this cool data. I was wondering if you had a codebook for this dataset, since the dbf seems to have interesting covariates - 151 columns [e.g. public goods, education etc]. Shapefiles truncate the column names so heavily that it is hard to guess.

If you have the scripts you used to scrape this, I can figure it out for myself by looking through which sub-portal on the i-Bhugoal site the scraper is pulling each covariate out of.

Thanks again; your github is a goldmine. I'll definitely credit and cite you if I ever manage to write a paper with any of the data you've posted.

**Comment by justinelliotmeyers** [comment]
@apoorvalal uploading GEOJSON now. Cheers!

**Comment by apoorvalal** [comment]
Great! Thanks a lot for the prompt response.

**Comment by apoorvalal** [comment]
Column names are the same as before [<= 10 chars, not very informative] unfortunately. Would you mind sharing the scraping scripts? I can try to rerun if you write directly to a shapefile and so don't have the full columnames handy

**Comment by justinelliotmeyers** [comment]
@apoorvalal sorry about that. I just double checked the raw data. The field names are exactly the way they appear in the newly uploaded geojson. Let me see if there is a way to join other data to this to get better attributes. I know there are some tables on the census site that have detailed attributes. I tried to find the population data earlier today with no luck (**although I know they exist). There is data about households here: http://censusindia.gov.in/2011census/HLO/HL_PCA/Houselisting-housing-HLPCA.html  One other thing to mention is, the way the india census data comes is somewhat standardized. They typically use the same structure of fields and order. Hopefully that can help you in the meantime.   These may be total populations: http://censusindia.gov.in/pca/cdb_pca_census/Houselisting-housing-BR.html

Let me know if these work for you. Census codes do not appear to join to these, so additional work may need to be done to match.

**Comment by apoorvalal** [comment]
Got it. I'll do some digging around later this month and send you a pull request with a codebook if I manage to put together one. thanks again!
